import { ClothingItem } from "@/components/ClothingCard";

export const clothingItems: ClothingItem[] = [
	{
		id: 1,
		name: "Camiseta Classic Fit",
		price: 79.9,
		originalPrice: 119.9,
		category: "Camisetas",
		color: "Branco",
		sizes: ["P", "M", "G", "GG"],
		emoji: "👕",
		gradient: "bg-gradient-to-br from-blue-100 to-purple-100",
	},
	{
		id: 2,
		name: "Jaqueta Jeans Premium",
		price: 259.9,
		category: "Jaquetas",
		color: "Azul",
		sizes: ["P", "M", "G"],
		emoji: "🧥",
		gradient: "bg-gradient-to-br from-indigo-100 to-blue-100",
	},
	{
		id: 3,
		name: "Vestido Floral Elegante",
		price: 189.9,
		originalPrice: 249.9,
		category: "Vestidos",
		color: "Rosa",
		sizes: ["PP", "P", "M", "G"],
		emoji: "👗",
		gradient: "bg-gradient-to-br from-pink-100 to-rose-100",
	},
	{
		id: 4,
		name: "Calça Slim Stretch",
		price: 149.9,
		category: "Calças",
		color: "Preto",
		sizes: ["38", "40", "42", "44"],
		emoji: "👖",
		gradient: "bg-gradient-to-br from-gray-100 to-slate-200",
	},
	{
		id: 5,
		name: "Moletom Oversized",
		price: 199.9,
		originalPrice: 259.9,
		category: "Moletons",
		color: "Cinza",
		sizes: ["M", "G", "GG"],
		emoji: "🧶",
		gradient: "bg-gradient-to-br from-amber-100 to-orange-100",
	},
	{
		id: 6,
		name: "Saia Midi Plissada",
		price: 129.9,
		category: "Saias",
		color: "Verde",
		sizes: ["PP", "P", "M"],
		emoji: "🩱",
		gradient: "bg-gradient-to-br from-emerald-100 to-teal-100",
	},
	{
		id: 7,
		name: "Blazer Executivo",
		price: 349.9,
		category: "Blazers",
		color: "Marinho",
		sizes: ["P", "M", "G", "GG"],
		emoji: "🤵",
		gradient: "bg-gradient-to-br from-slate-200 to-zinc-200",
	},
	{
		id: 8,
		name: "Camisa Social Slim",
		price: 119.9,
		originalPrice: 159.9,
		category: "Camisas",
		color: "Branco",
		sizes: ["P", "M", "G"],
		emoji: "👔",
		gradient: "bg-gradient-to-br from-sky-100 to-cyan-100",
	},
	{
		id: 9,
		name: "Shorts Casual",
		price: 89.9,
		category: "Shorts",
		color: "Bege",
		sizes: ["P", "M", "G", "GG"],
		emoji: "🩳",
		gradient: "bg-gradient-to-br from-yellow-100 to-amber-100",
	},
	{
		id: 10,
		name: "Casaco de Inverno",
		price: 399.9,
		originalPrice: 499.9,
		category: "Casacos",
		color: "Preto",
		sizes: ["M", "G", "GG"],
		emoji: "🧥",
		gradient: "bg-gradient-to-br from-violet-100 to-purple-100",
	},
	{
		id: 11,
		name: "Regata Fitness",
		price: 59.9,
		category: "Regatas",
		color: "Vermelho",
		sizes: ["PP", "P", "M", "G"],
		emoji: "🎽",
		gradient: "bg-gradient-to-br from-red-100 to-orange-100",
	},
	{
		id: 12,
		name: "Polo Ralph Style",
		price: 139.9,
		category: "Polos",
		color: "Verde",
		sizes: ["P", "M", "G"],
		emoji: "👕",
		gradient: "bg-gradient-to-br from-green-100 to-lime-100",
	},
];
